git-svn-id: https://svn.tdr.iem.uni-due.de:8443/svn/sctp/trunk/rsplib2@1264 516812f1-d3fd-0310-9ea4-9aededebcb87

diff --git a/rsplib/create-binaries b/rsplib/create-binaries
--- a/rsplib/create-binaries
+++ b/rsplib/create-binaries
@@ -35,7 +35,12 @@ fi
 rm -rf $DISTNAME-bin.tar.bz2 bin/
 
 cd ..
+rm -f *.tar.gz   # Entferne alte Dists!
 make dist
+if [ ! -e $DISTNAME.tar.gz ] ; then
+   echo "ERROR: Unable to create distribution $DISTNAME! Is this the correct version?"
+   exit 1
+fi
 cd $DISTDIRNAME
 
 
