git-svn-id: https://svn.tdr.iem.uni-due.de:8443/svn/sctp/trunk/rsplib2@1195 516812f1-d3fd-0310-9ea4-9aededebcb87

diff --git a/rsplib/filter-hosts b/rsplib/filter-hosts
--- a/rsplib/filter-hosts
+++ b/rsplib/filter-hosts
@@ -4,34 +4,42 @@
 
 
 showbad=0
-testhosts=0
-if [ "x$1" = "x-showbad" ] ; then
-   shift
-   showbad=1
-   testhosts=0
-elif [ "x$1" = "x-test" ] ; then
-   shift
-   showbad=1
-   testhosts=1
-fi
+showhosts=0
 
-SERVER_LIST=`\
-( \
+
+SERVER_TEST_OUTPUT=/dev/null
+SERVER_LIST=""
 while [ x$1 != "x" ] ; do \
-   echo $1 && \
-   shift ; \
-done \
-) | sort -u`
+   arg=`echo $1 | grep -- "^-"`
+   if [ "x$arg" = "x" ] ; then
+      SERVER_LIST="$SERVER_LIST $1"
+   else
+      if [ "x$1" = "x-showbad" ] ; then
+         showbad=1
+      elif [ "x$1" = "x-showhosts" ] ; then
+         showhosts=1
+      elif [ "x$1" = "x-showoutput" ] ; then
+         SERVER_TEST_OUTPUT=/dev/stderr
+      else
+         echo "ERROR: Bad parameter $1"
+         exit 1
+      fi
+   fi
+   shift
+done
+SERVER_LIST=`echo $SERVER_LIST | xargs -xn1 | sort -u`
 
 
 good=0
 bad=0
 for SERVER in $SERVER_LIST; do
    isgood=0
-   if [ $testhosts = 1 ] ; then
+   if [ $showhosts = 1 ] ; then
       echo "# Testing $SERVER ..."
    fi
-   if ssh -C -i $PLANETLAB_KEY -oPasswordAuthentication=no $PLANETLAB_USER@$SERVER "echo \"$SERVER is ready!\"" 2>/dev/null 1>/dev/null ; then
+   ./execalarm $SERVER_TEST_TIMEOUT "ssh -C -i $PLANETLAB_KEY -oPasswordAuthentication=no $PLANETLAB_USER@$SERVER \"$SERVER_TEST && echo \\\"$SERVER is ready!\\\"\"" 1>$SERVER_TEST_OUTPUT 2>$SERVER_TEST_OUTPUT
+   result=$?
+   if [ $result -eq 0 ]  ; then
       isgood=1
    fi
 
@@ -48,4 +56,8 @@ done
 
 if [ $showbad = 1 ] ; then
    echo "# Good: $good   Bad: $bad"
+fi
+
+if [ $bad -gt 0 ] ; then
+   exit 1
 fi
