git-svn-id: https://svn.tdr.iem.uni-due.de:8443/svn/sctp/trunk/rsplib2@1138 516812f1-d3fd-0310-9ea4-9aededebcb87

diff --git a/rsplib/start-process b/rsplib/start-process
--- a/rsplib/start-process
+++ b/rsplib/start-process
@@ -63,20 +63,23 @@ while [ ! x$1 = "x" ] ; do
    # Option -t sorgt dafür, daß Pseudo-Terminal erzeugt wird.
    # Optionen -t -t erzwingen Erstellung von Pseudo-Terminal, auch wenn stdin keines ist!
    # -> Lokaler ssh-Abbruch -> Abbruch der entfernten Prozesse.
-   ssh -t -t -C -i $PLANETLAB_KEY -oPasswordAuthentication=no $PLANETLAB_USER@$SERVER " \
-      cd ~/bin && \
-      ulimit -c unlimited && \
-      echo \"`date`: Login on $SERVER!\" && \
-      if [ \"x$PROGCHK\" = \"x1\" ] ; then \
-         MD5_REMOTE=\"\`md5sum $DISTPRGS\`\" && \
-         if [ \"x$MD5_LOCAL\" != \"x\$MD5_REMOTE\" ] ; then \
-            echo \"ERROR: Different program versions!\" ; \
-            echo \"local:  $MD5_LOCAL\" ; \
-            echo \"remote: \$MD5_REMOTE\" ; \
-            exit 1 ; \
-         fi \
-      fi && \
-      echo \"$SERVER> $PROGCALL\" && \
-      $PROGCALL" &
-   echo $! >$PIDFILE
+   ( ssh -t -t -C -i $PLANETLAB_KEY -oPasswordAuthentication=no $PLANETLAB_USER@$SERVER " \
+        cd ~/bin && \
+        ulimit -c unlimited && \
+        if [ \"x$PROGCHK\" = \"x1\" ] ; then \
+           MD5_REMOTE=\"\`md5sum $DISTPRGS\`\" && \
+           if [ \"x$MD5_LOCAL\" != \"x\$MD5_REMOTE\" ] ; then \
+              echo \"ERROR on $SERVER: Different program versions!\" ; \
+              echo \"local:  $MD5_LOCAL\" ; \
+              echo \"remote: \$MD5_REMOTE\" ; \
+              exit 1 ; \
+           fi \
+        fi && \
+        echo \"`date`: $SERVER> $PROGCALL\" | head -c117 | xargs -i§ echo §... && \
+        $PROGCALL" 2>&1 &
+     echo $! >$PIDFILE )  | grep -v "tcgetattr: Inappropriate ioctl for device" &
+   # This is necessary to get rid of the stupid tcgetattr error prints, but
+   # store ssh's PID instead of grep's PID!
+
+   # echo `date`: START `cat $PIDFILE` -- $PROCNAME >$RANDOM-$RANDOM.td0
 done
