git-svn-id: https://svn.tdr.iem.uni-due.de:8443/svn/sctp/trunk/rsplib2@1900 516812f1-d3fd-0310-9ea4-9aededebcb87

diff --git a/rsplib/planetlab/attack-scenario1 b/rsplib/planetlab/attack-scenario1
--- a/rsplib/planetlab/attack-scenario1
+++ b/rsplib/planetlab/attack-scenario1
@@ -36,6 +36,14 @@ else
    echo >&2 "ERROR: servicecontrol not found!"
    exit 1
 fi
+if [ -e ./ssh-tool ] ; then
+   SSH_TOOL_CMD=./ssh-tool
+elif [ -e ../../ssh-tool ] ; then
+   SSH_TOOL_CMD=../../ssh-tool
+else
+   echo >&2 "ERROR: ssh-tool not found!"
+   exit 1
+fi
 
 
 SSH_USER=$PLANETLAB_USER
@@ -47,11 +55,12 @@ SSH_USER="dreibh"
 SSH_KEY="/home/dreibh/.ssh/test-key"
 SERVICE_DIRECTORY="src/rsplib2/rsplib"
 SERVICE_PRE_PROGRAM=""
+OPT_CSP="-cspserver=127.0.0.1:2960 -cspinterval=1000"
 
 
 check_variable ()
 {
-   if [ "$1" == "" ] ; then
+   if [ "$1" = "" ] ; then
       echo >&2 "ERROR: Variable $1 is not set!"
       exit 1
    fi
@@ -59,9 +68,11 @@ check_variable ()
 }
 
 
+# echo "==== TEST ONLY ==== !!!!!!!!!!!!!!!!!!!!"
+# Duration=30
 # PRs=1
-# PEs=4
-# PUs=6
+# PEs=5
+# PUs=10
 # Policy="LeastUsed"
 # MaxBadPEReports=3
 # JobInterval=30.0
@@ -71,6 +82,7 @@ check_variable ()
 # AttackInterval=1
 # AttackIdentifier=0
 # AttackReportUnreachableProbability=0.0
+# echo "==== TEST ONLY ==== !!!!!!!!!!!!!!!!!!!!"
 
 check_variable Duration $Duration
 check_variable PRs $PRs
@@ -116,7 +128,7 @@ get_nodes ()
 }
 
 
-# UsefulNodes1="`(grep ".de$" great-planetlab.hosts ; grep ".edu$" great-planetlab.hosts) | sort -u`"
+# UsefulNodes1="`(grep ".de$" great-planetlab.hosts ; grep ".edu$" great-planetlab.hosts) | xargs -n1 echo | sort -u`"
 # UsefulNodes2="`(grep ".de$" great-planetlab.hosts ; grep ".edu$" great-planetlab.hosts) | sort -ru`"
 # echo $UsefulNodes
 
@@ -148,10 +160,16 @@ echo PU_PROpt=$PU_PROpt
 
 echo "###### Starting PRs ###################################################"
 id=1
-for pr in $PRList ; do
-   $SERVICE_CONTROL_CMD restart   "ssh" $pr  $SSH_NODE $SSH_USER $SSH_KEY   $ID-$id $SERVICE_DIRECTORY registrar \
-      "-loglevel=5 -asap=[::]:3863 -enrp=[::]:9901 -asapannounce=off -enrpannounce=off -maxbadpereports=$MaxBadPEReports $OPT_CSP $PR_PROpt"   "$SERVICE_PRE_PROGRAM" &
+for node in `echo $PRList | xargs -n1 echo | sort -u` ; do
+   rm -f $node-pr-start.cmd
+done
+for node in $PRList ; do
+   $SERVICE_CONTROL_CMD restart   "$SSH_TOOL_CMD WriteCmd $node-pr-start.cmd"  $node  $SSH_NODE $SSH_USER $SSH_KEY   $ID-$id $SERVICE_DIRECTORY registrar \
+      "-loglevel=5 -asap=[::]:3863 -enrp=[::]:9901 -asapannounce=off -enrpannounce=off -maxbadpereports=$MaxBadPEReports $OPT_CSP $PR_PROpt"   "$SERVICE_PRE_PROGRAM"
    let id=$id+1
+done
+for node in `echo $PRList | xargs -n1 echo | sort -u` ; do
+   $SSH_TOOL_CMD RunCmd $node-pr-start.cmd  $node  $SSH_NODE $SSH_USER $SSH_KEY &
 done
 wait
 
@@ -159,10 +177,16 @@ sleep 6
 
 echo "###### Starting attackers #############################################"
 id=1
-for pr in $AttackerList ; do
-   $SERVICE_CONTROL_CMD restart   "ssh" $pr  $SSH_NODE $SSH_USER $SSH_KEY   $ID-$id $SERVICE_DIRECTORY attacker \
-      "-type=$AttackType -interval=$AttackInterval -identifier=$AttackIdentifier -policy=$Policy -reportunreachableprobability=$AttackReportUnreachableProbability $OPT_CSP $PE_PROpt"   "$SERVICE_PRE_PROGRAM" &
+for node in `echo $AttackerList | xargs -n1 echo | sort -u` ; do
+   rm -f $node-attacker-start.cmd
+done
+for node in $AttackerList ; do
+   $SERVICE_CONTROL_CMD restart   "$SSH_TOOL_CMD WriteCmd $node-attacker-start.cmd"  $node  $SSH_NODE $SSH_USER $SSH_KEY   $ID-$id $SERVICE_DIRECTORY attacker \
+      "-type=$AttackType -interval=$AttackInterval -identifier=$AttackIdentifier -policy=$Policy -reportunreachableprobability=$AttackReportUnreachableProbability $OPT_CSP $PE_PROpt"   "$SERVICE_PRE_PROGRAM"
    let id=$id+1
+done
+for node in `echo $AttackerList | xargs -n1 echo | sort -u` ; do
+   $SSH_TOOL_CMD RunCmd $node-attacker-start.cmd  $node  $SSH_NODE $SSH_USER $SSH_KEY &
 done
 wait
 
@@ -170,10 +194,18 @@ sleep 6
 
 echo "###### Starting PEs ###################################################"
 id=1
-for pe in $PEList ; do
-   $SERVICE_CONTROL_CMD restart   "ssh" $pe  $SSH_NODE $SSH_USER $SSH_KEY   $ID-$id $SERVICE_DIRECTORY server \
-      "-loglevel=5 -calcapp -capcapacity=1000000 -policy=$Policy "-capobject=scenario.calcAppPoolElement[$id]" -capscalar=$ID-pe-$id.sca $PE_PROpt $OPT_CSP"   "$SERVICE_PRE_PROGRAM" &
+for node in `echo $PEList | xargs -n1 echo | sort -u` ; do
+   rm -f $node-pe-start.cmd
+done
+for node in $PEList ; do
+   $SERVICE_CONTROL_CMD restart   "$SSH_TOOL_CMD WriteCmd $node-pe-start.cmd"  $node  $SSH_NODE $SSH_USER $SSH_KEY   $ID-$id $SERVICE_DIRECTORY server \
+      "-loglevel=5 -calcapp -capcapacity=1000000 -policy=$Policy "-capobject=scenario.calcAppPoolElement[$id]" -capscalar=$ID-pe-$id.sca $PE_PROpt $OPT_CSP"   "$SERVICE_PRE_PROGRAM"
    let id=$id+1
+done
+v=1
+for node in `echo $PEList | xargs -n1 echo | sort -u` ; do
+   $SSH_TOOL_CMD RunCmd $node-pe-start.cmd  $node  $SSH_NODE $SSH_USER $SSH_KEY &
+   let v=$v+1
 done
 wait
 
@@ -181,10 +213,16 @@ sleep 6
 
 echo "###### Starting PUs ###################################################"
 id=1
-for attacker in $PUList ; do
-   $SERVICE_CONTROL_CMD restart   "ssh" $attacker  $SSH_NODE $SSH_USER $SSH_KEY   $ID-$id $SERVICE_DIRECTORY calcappclient \
-      "-loglevel=5 -jobsize=$JobSize -jobinterval=$JobInterval "-object=scenario.calcAppPoolUser[$id]" -scalar=$ID-pu-$id.sca $PE_PROpt $OPT_CSP"   "$SERVICE_PRE_PROGRAM" &
+for node in `echo $PUList | xargs -n1 echo | sort -u` ; do
+   rm -f $node-pu-start.cmd
+done
+for node in $PUList ; do
+   $SERVICE_CONTROL_CMD restart   "$SSH_TOOL_CMD WriteCmd $node-pu-start.cmd"  $node  $SSH_NODE $SSH_USER $SSH_KEY   $ID-$id $SERVICE_DIRECTORY calcappclient \
+      "-loglevel=5 -jobsize=$JobSize -jobinterval=$JobInterval "-object=scenario.calcAppPoolUser[$id]" -scalar=$ID-pu-$id.sca $PE_PROpt $OPT_CSP"   "$SERVICE_PRE_PROGRAM"
    let id=$id+1
+done
+for node in `echo $PUList | xargs -n1 echo | sort -u` ; do
+   $SSH_TOOL_CMD RunCmd $node-pu-start.cmd  $node  $SSH_NODE $SSH_USER $SSH_KEY &
 done
 wait
 
@@ -194,36 +232,60 @@ sleep $Duration
 
 echo "###### Stopping PUs ###################################################"
 id=1
-for pu in $PUList ; do
-   $SERVICE_CONTROL_CMD stop   "ssh" $pu  $SSH_NODE $SSH_USER $SSH_KEY   $ID-$id $SERVICE_DIRECTORY calcappclient ""   "$SERVICE_PRE_PROGRAM" &
+for node in `echo $PUList | xargs -n1 echo | sort -u` ; do
+   rm -f $node-pu-stop.cmd
+done
+for node in $PUList ; do
+   $SERVICE_CONTROL_CMD stop  "$SSH_TOOL_CMD WriteCmd $node-pu-stop.cmd"  $node  $SSH_NODE $SSH_USER $SSH_KEY   $ID-$id $SERVICE_DIRECTORY calcappclient ""   "$SERVICE_PRE_PROGRAM"
    let id=$id+1
+done
+for node in `echo $PUList | xargs -n1 echo | sort -u` ; do
+   $SSH_TOOL_CMD RunCmd $node-pu-stop.cmd  $node  $SSH_NODE $SSH_USER $SSH_KEY &
 done
 wait
 
 
 echo "###### Stopping PEs ###################################################"
 id=1
-for pe in $PEList ; do
-   $SERVICE_CONTROL_CMD stop   "ssh" $pe  $SSH_NODE $SSH_USER $SSH_KEY   $ID-$id $SERVICE_DIRECTORY server ""   "$SERVICE_PRE_PROGRAM" &
+for node in `echo $PEList | xargs -n1 echo | sort -u` ; do
+   rm -f $node-pe-stop.cmd
+done
+for node in $PEList ; do
+   $SERVICE_CONTROL_CMD stop  "$SSH_TOOL_CMD WriteCmd $node-pe-stop.cmd"  $node  $SSH_NODE $SSH_USER $SSH_KEY   $ID-$id $SERVICE_DIRECTORY server ""   "$SERVICE_PRE_PROGRAM"
    let id=$id+1
+done
+for node in `echo $PEList | xargs -n1 echo | sort -u` ; do
+   $SSH_TOOL_CMD RunCmd $node-pe-stop.cmd  $node  $SSH_NODE $SSH_USER $SSH_KEY &
 done
 wait
 
 
 echo "###### Stopping attackers #############################################"
 id=1
-for attacker in $AttackerList ; do
-   $SERVICE_CONTROL_CMD stop   "ssh" $attacker  $SSH_NODE $SSH_USER $SSH_KEY   $ID-$id $SERVICE_DIRECTORY attacker ""   "$SERVICE_PRE_PROGRAM" &
+for node in `echo $AttackerList | xargs -n1 echo | sort -u` ; do
+   rm -f $node-attacker-stop.cmd
+done
+for node in $AttackerList ; do
+   $SERVICE_CONTROL_CMD stop  "$SSH_TOOL_CMD WriteCmd $node-attacker-stop.cmd"  $node  $SSH_NODE $SSH_USER $SSH_KEY   $ID-$id $SERVICE_DIRECTORY attacker ""   "$SERVICE_PRE_PROGRAM"
    let id=$id+1
+done
+for node in `echo $AttackerList | xargs -n1 echo | sort -u` ; do
+   $SSH_TOOL_CMD RunCmd $node-attacker-stop.cmd  $node  $SSH_NODE $SSH_USER $SSH_KEY &
 done
 wait
 
 
 echo "###### Stopping PRs ###################################################"
 id=1
-for pr in $PRList ; do
-   $SERVICE_CONTROL_CMD stop   "ssh" $pr  $SSH_NODE $SSH_USER $SSH_KEY   $ID-$id $SERVICE_DIRECTORY registrar ""   "$SERVICE_PRE_PROGRAM" &
+for node in `echo $PRList | xargs -n1 echo | sort -u` ; do
+   rm -f $node-pr-stop.cmd
+done
+for node in $PRList ; do
+   $SERVICE_CONTROL_CMD stop  "$SSH_TOOL_CMD WriteCmd $node-pr-stop.cmd"  $node  $SSH_NODE $SSH_USER $SSH_KEY   $ID-$id $SERVICE_DIRECTORY registrar ""   "$SERVICE_PRE_PROGRAM"
    let id=$id+1
+done
+for node in `echo $PRList | xargs -n1 echo | sort -u` ; do
+   $SSH_TOOL_CMD RunCmd $node-pr-stop.cmd  $node  $SSH_NODE $SSH_USER $SSH_KEY &
 done
 wait
 
@@ -240,7 +302,7 @@ allNodes="`
    for pu in $PUList ; do
       echo $pu
    done
-) | sort -u`"
+) | xargs -n1 echo | sort -u`"
 
 for node in $allNodes ; do
    scp -C -i $SSH_KEY -oConnectTimeout=5 -oConnectionAttempts=4 -oStrictHostKeyChecking=no -oPasswordAuthentication=no "$SSH_USER@$node:$SERVICE_DIRECTORY/$ID-*.sca" . &
