git-svn-id: https://svn.tdr.iem.uni-due.de:8443/svn/sctp/trunk/rsplib2@1902 516812f1-d3fd-0310-9ea4-9aededebcb87

diff --git a/rsplib/planetlab/servicecontrol b/rsplib/planetlab/servicecontrol
--- a/rsplib/planetlab/servicecontrol
+++ b/rsplib/planetlab/servicecontrol
@@ -25,6 +25,13 @@ if [ $# -lt 9 ] ; then
    exit 1
 fi
 
+# NOTE:
+# "ps -p ..." only returns the command name. If it is too long, it is truncated!
+# In this case, a following grep for the full executable name will fail.
+# Therefore, this script uses "ps -o cmd -p ..." to get the executable name for
+# grep. There may be a problem if the *arguments* of another program using the
+# same # PID contain the original executable name...
+
 
 SC_ACTION="$1"
 
@@ -71,18 +78,18 @@ $SC_SSH_COMMAND -x -T -C -l $SC_SSH_USER -i $SC_SSH_KEY $SC_SSH_OPTS $SC_SSH_NOD
          if [ -e $SC_SERVICE_PIDFILE ] ; then
             echo -e "\\\x1b[034mStopping $SC_SERVICE_PROGRAM on \$HOSTNAME ($SC_SERVICE_PIDFILE) ...\\\x1b[030m"
             PID="\`cat $SC_SERVICE_PIDFILE\`"
-            if ps -p "\$PID" | grep $SC_SERVICE_PROGRAM 1>/dev/null 2>/dev/null ; then
+            if ps -o cmd -p "\$PID" | grep $SC_SERVICE_PROGRAM 1>/dev/null 2>/dev/null ; then
                $SC_SERVICE_PRE_PROGRAM kill -INT \$PID
                sleep 0.1
                i=0 ; while [ \$i -lt $SC_SERVICE_SHUTDOWN_TIMEOUT ] ; do
-                  if ! ps -p "\$PID" | grep $SC_SERVICE_PROGRAM 1>/dev/null 2>/dev/null ; then
+                  if ! ps -o cmd -p "\$PID" | grep $SC_SERVICE_PROGRAM 1>/dev/null 2>/dev/null ; then
                      i=$SC_SERVICE_SHUTDOWN_TIMEOUT
                   else
                      sleep 1
                   fi
                   let i=\$i+1
                done
-               if ps -p "\$PID" | grep $SC_SERVICE_PROGRAM 1>/dev/null 2>/dev/null ; then
+               if ps -o cmd -p "\$PID" | grep $SC_SERVICE_PROGRAM 1>/dev/null 2>/dev/null ; then
                   echo "$SC_SERVICE_PROGRAM on \$HOSTNAME has not stopped yet -> sending SIGKILL."
                   $SC_SERVICE_PRE_PROGRAM kill -KILL \$PID
                fi
@@ -99,7 +106,7 @@ $SC_SSH_COMMAND -x -T -C -l $SC_SSH_USER -i $SC_SSH_KEY $SC_SSH_OPTS $SC_SSH_NOD
          if [ -e $SC_SERVICE_PIDFILE ] ; then
             echo "$SC_SERVICE_PIDFILE already exisits."
             PID="\`cat $SC_SERVICE_PIDFILE\`"
-            if ps -p "\$PID" | grep $SC_SERVICE_PROGRAM 1>/dev/null 2>/dev/null ; then
+            if ps -o cmd -p "\$PID" | grep $SC_SERVICE_PROGRAM 1>/dev/null 2>/dev/null ; then
                echo "$SC_SERVICE_PROGRAM is still running (PID \$PID)!"
                DoStartup=0
             else
@@ -116,7 +123,7 @@ $SC_SSH_COMMAND -x -T -C -l $SC_SSH_USER -i $SC_SSH_KEY $SC_SSH_OPTS $SC_SSH_NOD
 
             # Wait some time, for sudo/nice etc. to start the actual program
             i=0 ; while [ \$i -lt $SC_SERVICE_STARTUP_TIMEOUT ] ; do
-               if ps -p "\$PID" | grep $SC_SERVICE_PROGRAM 1>/dev/null 2>/dev/null ; then
+               if ps -o cmd -p "\$PID" | grep $SC_SERVICE_PROGRAM 1>/dev/null 2>/dev/null ; then
                   i=$SC_SERVICE_STARTUP_TIMEOUT
                else
                   sleep 1
@@ -124,7 +131,7 @@ $SC_SSH_COMMAND -x -T -C -l $SC_SSH_USER -i $SC_SSH_KEY $SC_SSH_OPTS $SC_SSH_NOD
                let i=\$i+1
             done
 
-            if ! ps -p "\$PID" | grep $SC_SERVICE_PROGRAM 1>/dev/null 2>/dev/null ; then
+            if ! ps -o cmd -p "\$PID" | grep $SC_SERVICE_PROGRAM 1>/dev/null 2>/dev/null ; then
                $SC_SERVICE_PRE_PROGRAM kill -KILL \$PID   # Just to make sure it is gone
                let ExitCode=\$ExitCode+1
             fi
@@ -134,7 +141,7 @@ $SC_SSH_COMMAND -x -T -C -l $SC_SSH_USER -i $SC_SSH_KEY $SC_SSH_OPTS $SC_SSH_NOD
       if [ "$SC_ACTION" = "status" ] ; then
          if [ -e $SC_SERVICE_PIDFILE ] ; then
             PID="\`cat $SC_SERVICE_PIDFILE\`"
-            if ps -p "\$PID" | grep $SC_SERVICE_PROGRAM 1>/dev/null 2>/dev/null ; then
+            if ps -o cmd -p "\$PID" | grep $SC_SERVICE_PROGRAM 1>/dev/null 2>/dev/null ; then
                echo -e "\\\x1b[032m$SC_SERVICE_PROGRAM on \$HOSTNAME is OK.\\\x1b[0m"
             else
                echo -e "\\\x1b[031m$SC_SERVICE_PROGRAM on \$HOSTNAME is DEAD.\\\x1b[0m"
