git-svn-id: https://svn.tdr.iem.uni-due.de:8443/svn/sctp/trunk/rsplib2@1956 516812f1-d3fd-0310-9ea4-9aededebcb87

diff --git a/rsplib/planetlab/servicecontrol b/rsplib/planetlab/servicecontrol
--- a/rsplib/planetlab/servicecontrol
+++ b/rsplib/planetlab/servicecontrol
@@ -116,24 +116,29 @@ $SC_SSH_COMMAND -x -T -C -l $SC_SSH_USER -i $SC_SSH_KEY $SC_SSH_OPTS $SC_SSH_NOD
          fi
 
          if [ \$DoStartup -eq 1 ] ; then
-            ulimit -c unlimited
-            $SC_SERVICE_PRE_PROGRAM nohup ./$SC_SERVICE_PROGRAM $SC_SERVICE_OPTS >$SC_SERVICE_LOGFILE 2>&1 &
-            PID=\$!
-            echo \$PID >$SC_SERVICE_PIDFILE
+            if [ -e ./$SC_SERVICE_PROGRAM ] ; then
+               ulimit -c unlimited
+               $SC_SERVICE_PRE_PROGRAM nohup ./$SC_SERVICE_PROGRAM $SC_SERVICE_OPTS >$SC_SERVICE_LOGFILE 2>&1 &
+               PID=\$!
+               echo \$PID >$SC_SERVICE_PIDFILE
 
-            # Wait some time, for sudo/nice etc. to start the actual program
-            i=0 ; while [ \$i -lt $SC_SERVICE_STARTUP_TIMEOUT ] ; do
-               if ps -o cmd -p "\$PID" | grep $SC_SERVICE_PROGRAM 1>/dev/null 2>/dev/null ; then
-                  i=$SC_SERVICE_STARTUP_TIMEOUT
-               else
-                  sleep 1
+               # Wait some time, for sudo/nice etc. to start the actual program
+               i=0 ; while [ \$i -lt $SC_SERVICE_STARTUP_TIMEOUT ] ; do
+                  if ps -o cmd -p "\$PID" | grep $SC_SERVICE_PROGRAM 1>/dev/null 2>/dev/null ; then
+                     i=$SC_SERVICE_STARTUP_TIMEOUT
+                  else
+                     sleep 1
+                  fi
+                  let i=\$i+1
+               done
+
+               if ! ps -o cmd -p "\$PID" | grep $SC_SERVICE_PROGRAM 1>/dev/null 2>/dev/null ; then
+                  $SC_SERVICE_PRE_PROGRAM kill -KILL \$PID   # Just to make sure it is gone
+                  let ExitCode=\$ExitCode+1
                fi
-               let i=\$i+1
-            done
-
-            if ! ps -o cmd -p "\$PID" | grep $SC_SERVICE_PROGRAM 1>/dev/null 2>/dev/null ; then
-               $SC_SERVICE_PRE_PROGRAM kill -KILL \$PID   # Just to make sure it is gone
+            else
                let ExitCode=\$ExitCode+1
+               echo -e "\\\x1b[031mERROR: No program $SC_SERVICE_DIRECTORY/$SC_SERVICE_PROGRAM on \$HOSTNAME!\\\x1b[030m"
             fi
          fi
       fi
@@ -153,6 +158,7 @@ $SC_SSH_COMMAND -x -T -C -l $SC_SSH_USER -i $SC_SSH_KEY $SC_SSH_OPTS $SC_SSH_NOD
 
    else
       let ExitCode=\$ExitCode+1
+      echo -e "\\\x1b[031mERROR: No directory $SC_SERVICE_DIRECTORY on \$HOSTNAME!\\\x1b[030m"
    fi
 
    # echo "Leaving $SC_SSH_NODE"
