Updated make-diff script.
git-svn-id: https://svn.tdr.iem.uni-due.de:8443/svn/sctp/trunk/rsplib2@2518 516812f1-d3fd-0310-9ea4-9aededebcb87

diff --git a/freebsd/rsplib/make-diff b/freebsd/rsplib/make-diff
--- a/freebsd/rsplib/make-diff
+++ b/freebsd/rsplib/make-diff
@@ -1,5 +1,5 @@
 #!/bin/sh
-# $Id: make-deb 2491 2011-02-02 14:18:35Z dreibh $
+# $Id$
 #
 # Free Packaging Test Script
 # Copyright (C) 2010-2011 by Thomas Dreibholz
@@ -40,8 +40,10 @@ for file in $PACKAGING_FILES ; do
    if [ -e /usr/ports/$CATEGORY/$PACKAGE/$file -a -e $file ] ; then
       diff -uN /usr/ports/$CATEGORY/$PACKAGE/$file $file >>$PACKAGE.diff
    else
-      echo >&2 "ERROR: Unable to compare /usr/ports/$CATEGORY/$PACKAGE/$file and $file"
-      exit 1
+      if [ -e /usr/ports/$CATEGORY/$PACKAGE/$file ] ; then
+         echo >&2 "ERROR: Unable to compare /usr/ports/$CATEGORY/$PACKAGE/$file and $file"
+         exit 1
+      fi
    fi
 done
 
