Fixes and improvements to the configure system.
git-svn-id: https://svn.tdr.iem.uni-due.de:8443/svn/sctp/trunk/rsplib2@2295 516812f1-d3fd-0310-9ea4-9aededebcb87

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -52,6 +52,10 @@ else
    echo >&2 "ERROR: No aclocal directory found!"
    exit 1
 fi
+if [ ! -e $ACLOCALDIR/pkg.m4 ] ; then
+   echo >&2 "ERROR: pkg.m4 not found in $ACLOCALDIR; install pkg-config first!"
+   exit 1
+fi
 
 if [ -e /usr/bin/aclocal ] ; then
    /usr/bin/aclocal -I $ACLOCALDIR
