Updated make-deb script.
git-svn-id: https://svn.tdr.iem.uni-due.de:8443/svn/sctp/trunk/rsplib2@2465 516812f1-d3fd-0310-9ea4-9aededebcb87

diff --git a/make-deb b/make-deb
--- a/make-deb
+++ b/make-deb
@@ -95,15 +95,15 @@ for DISTRIBUTION in $DISTRIBUTIONS ; do
    echo "------ Creating package for $DISTRIBUTION ------"
 
    success=1
-   cp $UPSTREAM_PACKAGE $PACKAGE\_$UPSTREAM_VERSION.orig.tar.gz && \
-   cp $UPSTREAM_PACKAGE $PACKAGE\_$OUTPUT_VERSION.orig.tar.gz && \
-   rm -rf $PACKAGE-$UPSTREAM_VERSION && \
-   rm -rf $PACKAGE-$UPSTREAM_VERSION.orig && \
-   tar xzf $UPSTREAM_PACKAGE && \
-   cp -r $PACKAGE-$UPSTREAM_VERSION $PACKAGE-$UPSTREAM_VERSION.orig && \
-   cp -r debian $PACKAGE-$UPSTREAM_VERSION && \
-   find $PACKAGE-$UPSTREAM_VERSION -name .svn | xargs --no-run-if-empty rm -rf && \
-   cd $PACKAGE-$UPSTREAM_VERSION && \
+   cp ${UPSTREAM_PACKAGE} ${PACKAGE}_${UPSTREAM_VERSION}.orig.tar.gz && \
+   cp ${UPSTREAM_PACKAGE} ${PACKAGE}_$OUTPUT_VERSION.orig.tar.gz && \
+   rm -rf ${PACKAGE}-${UPSTREAM_VERSION} && \
+   rm -rf ${PACKAGE}-${UPSTREAM_VERSION}.orig && \
+   tar xzf ${UPSTREAM_PACKAGE} && \
+   cp -r ${PACKAGE}-${UPSTREAM_VERSION} ${PACKAGE}-${UPSTREAM_VERSION}.orig && \
+   cp -r debian ${PACKAGE}-${UPSTREAM_VERSION} && \
+   find ${PACKAGE}-${UPSTREAM_VERSION} -name .svn | xargs --no-run-if-empty rm -rf && \
+   cd ${PACKAGE}-${UPSTREAM_VERSION} && \
    success=0
 
    if [ $success -ne 0 ] ; then
@@ -112,29 +112,48 @@ for DISTRIBUTION in $DISTRIBUTIONS ; do
 
    if [ "$DISTRIBUTION" != "default" ] ; then
       if [ "$DISTRIBUTION" = "unstable" -o "$DISTRIBUTION" = "testing" -o "$DISTRIBUTION" = "stable" ] ; then
-         sed -e "s/$INPUT_DISTRIBUTION;/$DISTRIBUTION;/1" -e "s/ubuntu[0-9]//1" <debian/changelog >debian/changelog.new
+         sed -e "s/$INPUT_DISTRIBUTION;/$DISTRIBUTION;/1" \
+             -e "s/ubuntu[0-9]//1" \
+             -e "/(LP: #/D" \
+             <debian/changelog >debian/changelog.new
+         # Debian: Remove Launchpad Bug IDs.
       else
          # Naming example: 2.7.7-0ubuntu1~natty1~ppa0
-         sed -e "s/$INPUT_DISTRIBUTION;/$DISTRIBUTION;/1" -e "s/$PACKAGE_VERSION/$PACKAGE_VERSION~${DISTRIBUTION}1~ppa0/1" <debian/changelog >debian/changelog.new
+         sed -e "s/$INPUT_DISTRIBUTION;/$DISTRIBUTION;/1" \
+             -e "s/$PACKAGE_VERSION/$PACKAGE_VERSION~${DISTRIBUTION}1~ppa0/1" \
+             -e "/(Closes: #/D" \
+             <debian/changelog >debian/changelog.new
+         # Ubuntu: Remove Debian Bug IDs.
       fi
       mv debian/changelog.new debian/changelog
 
       # ------ Old distributions not supporting new Debian format -----------
-      if [ "$DISTRIBUTION" = "dapper" -o "$DISTRIBUTION" = "edgy" -o "$DISTRIBUTION" = "hardy" -o "$DISTRIBUTION" = "intrepid" -o "$DISTRIBUTION" = "jaunty" ] ; then
+      if [ "$DISTRIBUTION" = "dapper"   -o \
+           "$DISTRIBUTION" = "edgy"     -o \
+           "$DISTRIBUTION" = "feisty"   -o \
+           "$DISTRIBUTION" = "hardy"    -o \
+           "$DISTRIBUTION" = "intrepid" -o \
+           "$DISTRIBUTION" = "jaunty" ] ; then
          rm -rf debian/source
       fi
       # ---------------------------------------------------------------------
    else
+      # Ubuntu: Remove Debian Bug IDs.
+      sed -e "/(Closes: #/D" \
+             <debian/changelog >debian/changelog.new
+      mv debian/changelog.new debian/changelog
       sed -e "s/^Maintainer:/Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>\nXSBC-Original-Maintainer:/g" <debian/control >debian/control.new
       mv debian/control.new debian/control
    fi
-
+exit 1
 
    echo ""
    echo "------ Creating diff file $PACKAGE-$PACKAGE_VERSION.diff.gz ------"
    (
       cd ..
-      diff -urN "--exclude=*~" "--exclude=.svn" "--exclude=.git" $PACKAGE-$UPSTREAM_VERSION.orig $PACKAGE-$UPSTREAM_VERSION | gzip -c >$PACKAGE-$PACKAGE_VERSION.diff.gz
+      diff -urN "--exclude=*~" "--exclude=.svn" "--exclude=.git" \
+         $PACKAGE-$UPSTREAM_VERSION.orig $PACKAGE-$UPSTREAM_VERSION \
+         | gzip -c >$PACKAGE-$PACKAGE_VERSION.diff.gz
    )
 
 
@@ -160,9 +179,16 @@ for DISTRIBUTION in $DISTRIBUTIONS ; do
 
    cd ..
 
-   DSC_FILE="`find . -name $PACKAGE\_$OUTPUT_VERSION-$DISTRIBUTION*.dsc`"
-   if [ ! -e $DSC_FILE ] ; then
-      echo "ERROR: No $PACKAGE\_$OUTPUT_VERSION-$DISTRIBUTION*.dsc file has been generated -> Aborting!"
+   if [ "$DISTRIBUTION" = "unstable" -o \
+        "$DISTRIBUTION" = "testing"  -o \
+        "$DISTRIBUTION" = "stable"   -o \
+        "$DISTRIBUTION" = "default" ] ; then
+      dscFile=`ls ${PACKAGE}_${PACKAGE_VERSION}.dsc | tail -n1`
+   else
+      dscFile=`ls ${PACKAGE}_${PACKAGE_VERSION}~${DISTRIBUTION}[0-9]~ppa[0-9].dsc | tail -n1`
+   fi
+   if [ ! -e $dscFile ] ; then
+      echo "ERROR: $dscFile has not been generated successfully -> Aborting!"
       exit 1
    fi
 
@@ -187,10 +213,14 @@ echo ""
 
 echo "Upload to PPA:"
 for DISTRIBUTION in $DISTRIBUTIONS ; do
-   if [ "$DISTRIBUTION" = "unstable" -o "$DISTRIBUTION" = "testing" -o "$DISTRIBUTION" = "stable" -o "$DISTRIBUTION" = "default" ] ; then
-      ppa="mentors"
+   if [ "$DISTRIBUTION" = "unstable" -o \
+        "$DISTRIBUTION" = "testing"  -o \
+        "$DISTRIBUTION" = "stable"   -o \
+        "$DISTRIBUTION" = "default" ] ; then
       if [ "$DISTRIBUTION" = "default" ] ; then
          ppa="revu"
+      else
+         ppa="mentors"
       fi
       changesFile=`ls ${PACKAGE}_${PACKAGE_VERSION}_source.changes | tail -n1`
    else
@@ -201,9 +231,21 @@ for DISTRIBUTION in $DISTRIBUTIONS ; do
 done
 echo ""
 
-echo "Build test:"
+
+
+if [ -e make-symbols ] ; then
+   echo "################################################################"
+   echo "Do not forget to run make-symbols after library version changes!"
+   echo "################################################################"
+   echo ""
+fi
+
+echo "Build Test Commands:"
 for DISTRIBUTION in $DISTRIBUTIONS ; do
-   if [ "$DISTRIBUTION" = "unstable" -o "$DISTRIBUTION" = "testing" -o "$DISTRIBUTION" = "stable" -o "$DISTRIBUTION" = "default" ] ; then
+   if [ "$DISTRIBUTION" = "unstable" -o \
+        "$DISTRIBUTION" = "testing"  -o \
+        "$DISTRIBUTION" = "stable"   -o \
+        "$DISTRIBUTION" = "default" ] ; then
       changesFilesPattern="${PACKAGE}_${PACKAGE_VERSION}_*.changes"
       dscFile=`ls ${PACKAGE}_${PACKAGE_VERSION}.dsc | tail -n1`
    else
